### ISSUE TITLE
v2比v1可读性强

### ISSUE THREAD

**Issue by chan1919** [PinkDoc/pson#1]
C++新手正在入门，V2可读性高了很多，V1看不太明白哈。加油，我先研究研究V2，再学学你的另一个httpd。
来自本科二年级

**Comment by PinkDoc** [comment]
v1就是用一个 char buffer[]来代替union，然后根据类型来placement new，不过目前实现有bug，这种实现的各方面都比v2好。
不过现在有个variant https://en.cppreference.com/w/cpp/utility/variant，代替我这种做法，我那个httpd我觉得写的不咋地，不要看了，直接看nginx吧。http://tengine.taobao.org/book/
