### ISSUE TITLE
准备集成一个微型单元测试框架

### ISSUE THREAD

**Issue by chan1919** [PinkDoc/pson#2]
我这两天在学习测试驱动开发，看了一两个简单的单元测试代码，想继承进来，或许需要一段时间去思索和练习。

**Comment by PinkDoc** [comment]
你好，pson用的是gtest测试 :-)

**Comment by chan1919** [comment]
> 你好，pson用的是gtest测试 :-)

你太快了😭 我还没学会你就写好了

**Comment by PinkDoc** [comment]
我最近在搞json-rpc，有兴趣吗 ：）

**Comment by chan1919** [comment]
> 我最近在搞json-rpc，有兴趣吗 ：）

有的 有的 主要是学习和提高自己 求带
